baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Green AI Model'
theme = "hugo-book"

[menu]
# [[menu.before]]
[[menu.after]]
  name = "Github"
  url = "https://github.com/Green-AI-Model/Green-AI-Model.github.io"
  weight = 10
