baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Green AI Model'
theme = "hugo-book"

[menu]
# [[menu.before]]
[[menu.after]]
  name = "Github"
  url = "https://github.com/Green-AI-Model/Green-AI-Model.github.io"
  weight = 100

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 2

[params]
  BookSection = 'docs'
  BookRepo = 'https://github.com/Green-AI-Model/Green-AI-Model.github.io'
  BookSearch = true
  BookTheme = 'auto'
  enableGitInfo = true